<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>2026.3.0</Version>
    <AssemblyName>Serara</AssemblyName>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="ZLogger" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Serara.Files\Serara.Files.csproj" />
    <ProjectReference Include="..\Serara.Hosting\Serara.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="$(Configuration)=='Debug'">
    <Content Include="config.debug.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
